#!/bin/sh

pgrep -x transmission-da >/dev/null || (transmission-daemon && notify-send "Starting transmission daemon..." && sleep 3)

# chosen=$(printf "Movie\\nOther" | dmenu -i -p "Select torrent type to add:")

transmission-remote -a "$@" && notify-send "Transmission Daemon" "Torrent added" 
